# Name of the workflow
name: Primeiro CI worflow

# Setting events that triggers our workflow
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]


# Permission to access/read the contents inside the repository
permissions:
    contents: read

jobs:
    # A job
    build:
        # The operation system to run the job
        runs-on: ubuntu-latest

        # Steps of the building workflow
        steps:
            # Just clone the entire repository to the virtual machine
            - name: Checkout repository
              uses: actions/checkout@v4
            
            # Set up python bacause ubuntu-latest does not have python installed
            - name: Set up python 3.10.7
              uses: actions/setup-python@v5
              with:
                python-version: '3.10.7'

            # Installing poetry
            - name: Install poetry
              run: |
                curl -sSL https://install.python-poetry.org | python3 -
                    export PATH=$HOME/.local/bin:$PATH

            # Install dependencies using poetry
            - name: Install dependencies
              run: poetry run make install

            # Lint with flake8
            - name: Lint with flake8
              run: poetry run make check